### ISSUE TITLE
XML2DataBase诸如此类的错误先检查是否对新添加到工程项目的cpp编译过了,自己在此被坑了一把

### ISSUE THREAD

**Issue by chenmingsf** [freeeyes/XML2DataBase#1]
LNK2019	无法解析的外部符号 "public: void __cdecl ConnPool::ReleaseOneConn(class MysqlEncap *)" 
(?ReleaseOneConn@ConnPool@@QEAAXPEAVMysqlEncap@@@Z)，
该符号在函数 "bool __cdecl select_tb_alluserinfo_for_pool(class std::vector<class CAllUserInfo_Table,
class std::allocator<class CAllUserInfo_Table> > &)" (?select_tb_alluserinfo_for_pool@@YA_NAEAV?$
vector@VCAllUserInfo_Table@@V?$allocator@VCAllUserInfo_Table@@@std@@@std@@@Z) 中被引用

**Comment by freeeyes** [comment]
引用工程编译目录查看一下。
